package com.pinyougou.mapper;

import com.pinyougou.pojo.AssetDetectData;
import com.pinyougou.pojo.AssetDetectDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AssetDetectDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_detect_data
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    long countByExample(AssetDetectDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_detect_data
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    int deleteByExample(AssetDetectDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_detect_data
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_detect_data
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    int insert(AssetDetectData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_detect_data
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    int insertSelective(AssetDetectData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_detect_data
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    List<AssetDetectData> selectByExample(AssetDetectDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_detect_data
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    AssetDetectData selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_detect_data
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    int updateByExampleSelective(@Param("record") AssetDetectData record, @Param("example") AssetDetectDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_detect_data
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    int updateByExample(@Param("record") AssetDetectData record, @Param("example") AssetDetectDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_detect_data
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    int updateByPrimaryKeySelective(AssetDetectData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_detect_data
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    int updateByPrimaryKey(AssetDetectData record);
}