package com.pinyougou.mapper;

import com.pinyougou.pojo.CentralOfficeServiceInformation;
import com.pinyougou.pojo.CentralOfficeServiceInformationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CentralOfficeServiceInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table central_office_service_information
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    long countByExample(CentralOfficeServiceInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table central_office_service_information
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    int deleteByExample(CentralOfficeServiceInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table central_office_service_information
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table central_office_service_information
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    int insert(CentralOfficeServiceInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table central_office_service_information
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    int insertSelective(CentralOfficeServiceInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table central_office_service_information
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    List<CentralOfficeServiceInformation> selectByExample(CentralOfficeServiceInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table central_office_service_information
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    CentralOfficeServiceInformation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table central_office_service_information
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    int updateByExampleSelective(@Param("record") CentralOfficeServiceInformation record, @Param("example") CentralOfficeServiceInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table central_office_service_information
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    int updateByExample(@Param("record") CentralOfficeServiceInformation record, @Param("example") CentralOfficeServiceInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table central_office_service_information
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    int updateByPrimaryKeySelective(CentralOfficeServiceInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table central_office_service_information
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    int updateByPrimaryKey(CentralOfficeServiceInformation record);
}