package com.pinyougou.pojo;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table asset_detect_data
 */
public class AssetDetectData {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_detect_data.id
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   运营单位名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_detect_data.operate_organization
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    private String operateOrganization;

    /**
     * Database Column Remarks:
     *   市
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_detect_data.city
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    private String city;

    /**
     * Database Column Remarks:
     *   ip
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_detect_data.ip
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    private String ip;

    /**
     * Database Column Remarks:
     *   port
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_detect_data.port
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    private String port;

    /**
     * Database Column Remarks:
     *   服务
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_detect_data.service
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    private String service;

    /**
     * Database Column Remarks:
     *   url
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_detect_data.url
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    private String url;

    /**
     * Database Column Remarks:
     *   状态码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_detect_data.status_code
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    private String statusCode;

    /**
     * Database Column Remarks:
     *   web title
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_detect_data.web_title
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    private String webTitle;

    /**
     * Database Column Remarks:
     *   域名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_detect_data.domain
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    private String domain;

    /**
     * Database Column Remarks:
     *   产品
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_detect_data.service_product
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    private String serviceProduct;

    /**
     * Database Column Remarks:
     *   服务版本
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_detect_data.service_version
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    private String serviceVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_detect_data.domain_cname
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    private String domainCname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_detect_data.is_cdn
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    private String isCdn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_detect_data.cdn_product
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    private String cdnProduct;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_detect_data.cdn_company
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    private String cdnCompany;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_detect_data.cdn_ssl_info
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    private String cdnSslInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_detect_data.response_header
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    private String responseHeader;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_detect_data.server
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    private String server;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_detect_data.ssl_subject
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    private String sslSubject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_detect_data.service_banner
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    private String serviceBanner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_detect_data.p_device_type
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    private String pDeviceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_detect_data.device_type
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    private String deviceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_detect_data.scan_time
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    private String scanTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_detect_data.country
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_detect_data.province
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_detect_data.is_alive
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    private String isAlive;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_detect_data.classify_1
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    private String classify1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column asset_detect_data.classify_2
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    private String classify2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_detect_data.id
     *
     * @return the value of asset_detect_data.id
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_detect_data.id
     *
     * @param id the value for asset_detect_data.id
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_detect_data.operate_organization
     *
     * @return the value of asset_detect_data.operate_organization
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    public String getOperateOrganization() {
        return operateOrganization;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_detect_data.operate_organization
     *
     * @param operateOrganization the value for asset_detect_data.operate_organization
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    public void setOperateOrganization(String operateOrganization) {
        this.operateOrganization = operateOrganization == null ? null : operateOrganization.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_detect_data.city
     *
     * @return the value of asset_detect_data.city
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_detect_data.city
     *
     * @param city the value for asset_detect_data.city
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_detect_data.ip
     *
     * @return the value of asset_detect_data.ip
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_detect_data.ip
     *
     * @param ip the value for asset_detect_data.ip
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_detect_data.port
     *
     * @return the value of asset_detect_data.port
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    public String getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_detect_data.port
     *
     * @param port the value for asset_detect_data.port
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    public void setPort(String port) {
        this.port = port == null ? null : port.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_detect_data.service
     *
     * @return the value of asset_detect_data.service
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    public String getService() {
        return service;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_detect_data.service
     *
     * @param service the value for asset_detect_data.service
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    public void setService(String service) {
        this.service = service == null ? null : service.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_detect_data.url
     *
     * @return the value of asset_detect_data.url
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_detect_data.url
     *
     * @param url the value for asset_detect_data.url
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_detect_data.status_code
     *
     * @return the value of asset_detect_data.status_code
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    public String getStatusCode() {
        return statusCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_detect_data.status_code
     *
     * @param statusCode the value for asset_detect_data.status_code
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    public void setStatusCode(String statusCode) {
        this.statusCode = statusCode == null ? null : statusCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_detect_data.web_title
     *
     * @return the value of asset_detect_data.web_title
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    public String getWebTitle() {
        return webTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_detect_data.web_title
     *
     * @param webTitle the value for asset_detect_data.web_title
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    public void setWebTitle(String webTitle) {
        this.webTitle = webTitle == null ? null : webTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_detect_data.domain
     *
     * @return the value of asset_detect_data.domain
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    public String getDomain() {
        return domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_detect_data.domain
     *
     * @param domain the value for asset_detect_data.domain
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    public void setDomain(String domain) {
        this.domain = domain == null ? null : domain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_detect_data.service_product
     *
     * @return the value of asset_detect_data.service_product
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    public String getServiceProduct() {
        return serviceProduct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_detect_data.service_product
     *
     * @param serviceProduct the value for asset_detect_data.service_product
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    public void setServiceProduct(String serviceProduct) {
        this.serviceProduct = serviceProduct == null ? null : serviceProduct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_detect_data.service_version
     *
     * @return the value of asset_detect_data.service_version
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    public String getServiceVersion() {
        return serviceVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_detect_data.service_version
     *
     * @param serviceVersion the value for asset_detect_data.service_version
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    public void setServiceVersion(String serviceVersion) {
        this.serviceVersion = serviceVersion == null ? null : serviceVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_detect_data.domain_cname
     *
     * @return the value of asset_detect_data.domain_cname
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    public String getDomainCname() {
        return domainCname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_detect_data.domain_cname
     *
     * @param domainCname the value for asset_detect_data.domain_cname
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    public void setDomainCname(String domainCname) {
        this.domainCname = domainCname == null ? null : domainCname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_detect_data.is_cdn
     *
     * @return the value of asset_detect_data.is_cdn
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    public String getIsCdn() {
        return isCdn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_detect_data.is_cdn
     *
     * @param isCdn the value for asset_detect_data.is_cdn
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    public void setIsCdn(String isCdn) {
        this.isCdn = isCdn == null ? null : isCdn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_detect_data.cdn_product
     *
     * @return the value of asset_detect_data.cdn_product
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    public String getCdnProduct() {
        return cdnProduct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_detect_data.cdn_product
     *
     * @param cdnProduct the value for asset_detect_data.cdn_product
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    public void setCdnProduct(String cdnProduct) {
        this.cdnProduct = cdnProduct == null ? null : cdnProduct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_detect_data.cdn_company
     *
     * @return the value of asset_detect_data.cdn_company
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    public String getCdnCompany() {
        return cdnCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_detect_data.cdn_company
     *
     * @param cdnCompany the value for asset_detect_data.cdn_company
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    public void setCdnCompany(String cdnCompany) {
        this.cdnCompany = cdnCompany == null ? null : cdnCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_detect_data.cdn_ssl_info
     *
     * @return the value of asset_detect_data.cdn_ssl_info
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    public String getCdnSslInfo() {
        return cdnSslInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_detect_data.cdn_ssl_info
     *
     * @param cdnSslInfo the value for asset_detect_data.cdn_ssl_info
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    public void setCdnSslInfo(String cdnSslInfo) {
        this.cdnSslInfo = cdnSslInfo == null ? null : cdnSslInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_detect_data.response_header
     *
     * @return the value of asset_detect_data.response_header
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    public String getResponseHeader() {
        return responseHeader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_detect_data.response_header
     *
     * @param responseHeader the value for asset_detect_data.response_header
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    public void setResponseHeader(String responseHeader) {
        this.responseHeader = responseHeader == null ? null : responseHeader.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_detect_data.server
     *
     * @return the value of asset_detect_data.server
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    public String getServer() {
        return server;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_detect_data.server
     *
     * @param server the value for asset_detect_data.server
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    public void setServer(String server) {
        this.server = server == null ? null : server.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_detect_data.ssl_subject
     *
     * @return the value of asset_detect_data.ssl_subject
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    public String getSslSubject() {
        return sslSubject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_detect_data.ssl_subject
     *
     * @param sslSubject the value for asset_detect_data.ssl_subject
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    public void setSslSubject(String sslSubject) {
        this.sslSubject = sslSubject == null ? null : sslSubject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_detect_data.service_banner
     *
     * @return the value of asset_detect_data.service_banner
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    public String getServiceBanner() {
        return serviceBanner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_detect_data.service_banner
     *
     * @param serviceBanner the value for asset_detect_data.service_banner
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    public void setServiceBanner(String serviceBanner) {
        this.serviceBanner = serviceBanner == null ? null : serviceBanner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_detect_data.p_device_type
     *
     * @return the value of asset_detect_data.p_device_type
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    public String getpDeviceType() {
        return pDeviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_detect_data.p_device_type
     *
     * @param pDeviceType the value for asset_detect_data.p_device_type
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    public void setpDeviceType(String pDeviceType) {
        this.pDeviceType = pDeviceType == null ? null : pDeviceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_detect_data.device_type
     *
     * @return the value of asset_detect_data.device_type
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    public String getDeviceType() {
        return deviceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_detect_data.device_type
     *
     * @param deviceType the value for asset_detect_data.device_type
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    public void setDeviceType(String deviceType) {
        this.deviceType = deviceType == null ? null : deviceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_detect_data.scan_time
     *
     * @return the value of asset_detect_data.scan_time
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    public String getScanTime() {
        return scanTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_detect_data.scan_time
     *
     * @param scanTime the value for asset_detect_data.scan_time
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    public void setScanTime(String scanTime) {
        this.scanTime = scanTime == null ? null : scanTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_detect_data.country
     *
     * @return the value of asset_detect_data.country
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_detect_data.country
     *
     * @param country the value for asset_detect_data.country
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_detect_data.province
     *
     * @return the value of asset_detect_data.province
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_detect_data.province
     *
     * @param province the value for asset_detect_data.province
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_detect_data.is_alive
     *
     * @return the value of asset_detect_data.is_alive
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    public String getIsAlive() {
        return isAlive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_detect_data.is_alive
     *
     * @param isAlive the value for asset_detect_data.is_alive
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    public void setIsAlive(String isAlive) {
        this.isAlive = isAlive == null ? null : isAlive.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_detect_data.classify_1
     *
     * @return the value of asset_detect_data.classify_1
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    public String getClassify1() {
        return classify1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_detect_data.classify_1
     *
     * @param classify1 the value for asset_detect_data.classify_1
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    public void setClassify1(String classify1) {
        this.classify1 = classify1 == null ? null : classify1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column asset_detect_data.classify_2
     *
     * @return the value of asset_detect_data.classify_2
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    public String getClassify2() {
        return classify2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column asset_detect_data.classify_2
     *
     * @param classify2 the value for asset_detect_data.classify_2
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    public void setClassify2(String classify2) {
        this.classify2 = classify2 == null ? null : classify2.trim();
    }
}