package com.pinyougou.pojo;

import java.util.ArrayList;
import java.util.List;

public class AssetDetectDataExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table asset_detect_data
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table asset_detect_data
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table asset_detect_data
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_detect_data
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    public AssetDetectDataExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_detect_data
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_detect_data
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_detect_data
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_detect_data
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_detect_data
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_detect_data
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_detect_data
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_detect_data
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_detect_data
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table asset_detect_data
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table asset_detect_data
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOperateOrganizationIsNull() {
            addCriterion("operate_organization is null");
            return (Criteria) this;
        }

        public Criteria andOperateOrganizationIsNotNull() {
            addCriterion("operate_organization is not null");
            return (Criteria) this;
        }

        public Criteria andOperateOrganizationEqualTo(String value) {
            addCriterion("operate_organization =", value, "operateOrganization");
            return (Criteria) this;
        }

        public Criteria andOperateOrganizationNotEqualTo(String value) {
            addCriterion("operate_organization <>", value, "operateOrganization");
            return (Criteria) this;
        }

        public Criteria andOperateOrganizationGreaterThan(String value) {
            addCriterion("operate_organization >", value, "operateOrganization");
            return (Criteria) this;
        }

        public Criteria andOperateOrganizationGreaterThanOrEqualTo(String value) {
            addCriterion("operate_organization >=", value, "operateOrganization");
            return (Criteria) this;
        }

        public Criteria andOperateOrganizationLessThan(String value) {
            addCriterion("operate_organization <", value, "operateOrganization");
            return (Criteria) this;
        }

        public Criteria andOperateOrganizationLessThanOrEqualTo(String value) {
            addCriterion("operate_organization <=", value, "operateOrganization");
            return (Criteria) this;
        }

        public Criteria andOperateOrganizationLike(String value) {
            addCriterion("operate_organization like", value, "operateOrganization");
            return (Criteria) this;
        }

        public Criteria andOperateOrganizationNotLike(String value) {
            addCriterion("operate_organization not like", value, "operateOrganization");
            return (Criteria) this;
        }

        public Criteria andOperateOrganizationIn(List<String> values) {
            addCriterion("operate_organization in", values, "operateOrganization");
            return (Criteria) this;
        }

        public Criteria andOperateOrganizationNotIn(List<String> values) {
            addCriterion("operate_organization not in", values, "operateOrganization");
            return (Criteria) this;
        }

        public Criteria andOperateOrganizationBetween(String value1, String value2) {
            addCriterion("operate_organization between", value1, value2, "operateOrganization");
            return (Criteria) this;
        }

        public Criteria andOperateOrganizationNotBetween(String value1, String value2) {
            addCriterion("operate_organization not between", value1, value2, "operateOrganization");
            return (Criteria) this;
        }

        public Criteria andCityIsNull() {
            addCriterion("city is null");
            return (Criteria) this;
        }

        public Criteria andCityIsNotNull() {
            addCriterion("city is not null");
            return (Criteria) this;
        }

        public Criteria andCityEqualTo(String value) {
            addCriterion("city =", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotEqualTo(String value) {
            addCriterion("city <>", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThan(String value) {
            addCriterion("city >", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThanOrEqualTo(String value) {
            addCriterion("city >=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThan(String value) {
            addCriterion("city <", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThanOrEqualTo(String value) {
            addCriterion("city <=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLike(String value) {
            addCriterion("city like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotLike(String value) {
            addCriterion("city not like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityIn(List<String> values) {
            addCriterion("city in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotIn(List<String> values) {
            addCriterion("city not in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityBetween(String value1, String value2) {
            addCriterion("city between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotBetween(String value1, String value2) {
            addCriterion("city not between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andIpIsNull() {
            addCriterion("ip is null");
            return (Criteria) this;
        }

        public Criteria andIpIsNotNull() {
            addCriterion("ip is not null");
            return (Criteria) this;
        }

        public Criteria andIpEqualTo(String value) {
            addCriterion("ip =", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotEqualTo(String value) {
            addCriterion("ip <>", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpGreaterThan(String value) {
            addCriterion("ip >", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpGreaterThanOrEqualTo(String value) {
            addCriterion("ip >=", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLessThan(String value) {
            addCriterion("ip <", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLessThanOrEqualTo(String value) {
            addCriterion("ip <=", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLike(String value) {
            addCriterion("ip like", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotLike(String value) {
            addCriterion("ip not like", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpIn(List<String> values) {
            addCriterion("ip in", values, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotIn(List<String> values) {
            addCriterion("ip not in", values, "ip");
            return (Criteria) this;
        }

        public Criteria andIpBetween(String value1, String value2) {
            addCriterion("ip between", value1, value2, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotBetween(String value1, String value2) {
            addCriterion("ip not between", value1, value2, "ip");
            return (Criteria) this;
        }

        public Criteria andPortIsNull() {
            addCriterion("port is null");
            return (Criteria) this;
        }

        public Criteria andPortIsNotNull() {
            addCriterion("port is not null");
            return (Criteria) this;
        }

        public Criteria andPortEqualTo(String value) {
            addCriterion("port =", value, "port");
            return (Criteria) this;
        }

        public Criteria andPortNotEqualTo(String value) {
            addCriterion("port <>", value, "port");
            return (Criteria) this;
        }

        public Criteria andPortGreaterThan(String value) {
            addCriterion("port >", value, "port");
            return (Criteria) this;
        }

        public Criteria andPortGreaterThanOrEqualTo(String value) {
            addCriterion("port >=", value, "port");
            return (Criteria) this;
        }

        public Criteria andPortLessThan(String value) {
            addCriterion("port <", value, "port");
            return (Criteria) this;
        }

        public Criteria andPortLessThanOrEqualTo(String value) {
            addCriterion("port <=", value, "port");
            return (Criteria) this;
        }

        public Criteria andPortLike(String value) {
            addCriterion("port like", value, "port");
            return (Criteria) this;
        }

        public Criteria andPortNotLike(String value) {
            addCriterion("port not like", value, "port");
            return (Criteria) this;
        }

        public Criteria andPortIn(List<String> values) {
            addCriterion("port in", values, "port");
            return (Criteria) this;
        }

        public Criteria andPortNotIn(List<String> values) {
            addCriterion("port not in", values, "port");
            return (Criteria) this;
        }

        public Criteria andPortBetween(String value1, String value2) {
            addCriterion("port between", value1, value2, "port");
            return (Criteria) this;
        }

        public Criteria andPortNotBetween(String value1, String value2) {
            addCriterion("port not between", value1, value2, "port");
            return (Criteria) this;
        }

        public Criteria andServiceIsNull() {
            addCriterion("service is null");
            return (Criteria) this;
        }

        public Criteria andServiceIsNotNull() {
            addCriterion("service is not null");
            return (Criteria) this;
        }

        public Criteria andServiceEqualTo(String value) {
            addCriterion("service =", value, "service");
            return (Criteria) this;
        }

        public Criteria andServiceNotEqualTo(String value) {
            addCriterion("service <>", value, "service");
            return (Criteria) this;
        }

        public Criteria andServiceGreaterThan(String value) {
            addCriterion("service >", value, "service");
            return (Criteria) this;
        }

        public Criteria andServiceGreaterThanOrEqualTo(String value) {
            addCriterion("service >=", value, "service");
            return (Criteria) this;
        }

        public Criteria andServiceLessThan(String value) {
            addCriterion("service <", value, "service");
            return (Criteria) this;
        }

        public Criteria andServiceLessThanOrEqualTo(String value) {
            addCriterion("service <=", value, "service");
            return (Criteria) this;
        }

        public Criteria andServiceLike(String value) {
            addCriterion("service like", value, "service");
            return (Criteria) this;
        }

        public Criteria andServiceNotLike(String value) {
            addCriterion("service not like", value, "service");
            return (Criteria) this;
        }

        public Criteria andServiceIn(List<String> values) {
            addCriterion("service in", values, "service");
            return (Criteria) this;
        }

        public Criteria andServiceNotIn(List<String> values) {
            addCriterion("service not in", values, "service");
            return (Criteria) this;
        }

        public Criteria andServiceBetween(String value1, String value2) {
            addCriterion("service between", value1, value2, "service");
            return (Criteria) this;
        }

        public Criteria andServiceNotBetween(String value1, String value2) {
            addCriterion("service not between", value1, value2, "service");
            return (Criteria) this;
        }

        public Criteria andUrlIsNull() {
            addCriterion("url is null");
            return (Criteria) this;
        }

        public Criteria andUrlIsNotNull() {
            addCriterion("url is not null");
            return (Criteria) this;
        }

        public Criteria andUrlEqualTo(String value) {
            addCriterion("url =", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotEqualTo(String value) {
            addCriterion("url <>", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThan(String value) {
            addCriterion("url >", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThanOrEqualTo(String value) {
            addCriterion("url >=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThan(String value) {
            addCriterion("url <", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThanOrEqualTo(String value) {
            addCriterion("url <=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLike(String value) {
            addCriterion("url like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotLike(String value) {
            addCriterion("url not like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlIn(List<String> values) {
            addCriterion("url in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotIn(List<String> values) {
            addCriterion("url not in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlBetween(String value1, String value2) {
            addCriterion("url between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotBetween(String value1, String value2) {
            addCriterion("url not between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andStatusCodeIsNull() {
            addCriterion("status_code is null");
            return (Criteria) this;
        }

        public Criteria andStatusCodeIsNotNull() {
            addCriterion("status_code is not null");
            return (Criteria) this;
        }

        public Criteria andStatusCodeEqualTo(String value) {
            addCriterion("status_code =", value, "statusCode");
            return (Criteria) this;
        }

        public Criteria andStatusCodeNotEqualTo(String value) {
            addCriterion("status_code <>", value, "statusCode");
            return (Criteria) this;
        }

        public Criteria andStatusCodeGreaterThan(String value) {
            addCriterion("status_code >", value, "statusCode");
            return (Criteria) this;
        }

        public Criteria andStatusCodeGreaterThanOrEqualTo(String value) {
            addCriterion("status_code >=", value, "statusCode");
            return (Criteria) this;
        }

        public Criteria andStatusCodeLessThan(String value) {
            addCriterion("status_code <", value, "statusCode");
            return (Criteria) this;
        }

        public Criteria andStatusCodeLessThanOrEqualTo(String value) {
            addCriterion("status_code <=", value, "statusCode");
            return (Criteria) this;
        }

        public Criteria andStatusCodeLike(String value) {
            addCriterion("status_code like", value, "statusCode");
            return (Criteria) this;
        }

        public Criteria andStatusCodeNotLike(String value) {
            addCriterion("status_code not like", value, "statusCode");
            return (Criteria) this;
        }

        public Criteria andStatusCodeIn(List<String> values) {
            addCriterion("status_code in", values, "statusCode");
            return (Criteria) this;
        }

        public Criteria andStatusCodeNotIn(List<String> values) {
            addCriterion("status_code not in", values, "statusCode");
            return (Criteria) this;
        }

        public Criteria andStatusCodeBetween(String value1, String value2) {
            addCriterion("status_code between", value1, value2, "statusCode");
            return (Criteria) this;
        }

        public Criteria andStatusCodeNotBetween(String value1, String value2) {
            addCriterion("status_code not between", value1, value2, "statusCode");
            return (Criteria) this;
        }

        public Criteria andWebTitleIsNull() {
            addCriterion("web_title is null");
            return (Criteria) this;
        }

        public Criteria andWebTitleIsNotNull() {
            addCriterion("web_title is not null");
            return (Criteria) this;
        }

        public Criteria andWebTitleEqualTo(String value) {
            addCriterion("web_title =", value, "webTitle");
            return (Criteria) this;
        }

        public Criteria andWebTitleNotEqualTo(String value) {
            addCriterion("web_title <>", value, "webTitle");
            return (Criteria) this;
        }

        public Criteria andWebTitleGreaterThan(String value) {
            addCriterion("web_title >", value, "webTitle");
            return (Criteria) this;
        }

        public Criteria andWebTitleGreaterThanOrEqualTo(String value) {
            addCriterion("web_title >=", value, "webTitle");
            return (Criteria) this;
        }

        public Criteria andWebTitleLessThan(String value) {
            addCriterion("web_title <", value, "webTitle");
            return (Criteria) this;
        }

        public Criteria andWebTitleLessThanOrEqualTo(String value) {
            addCriterion("web_title <=", value, "webTitle");
            return (Criteria) this;
        }

        public Criteria andWebTitleLike(String value) {
            addCriterion("web_title like", value, "webTitle");
            return (Criteria) this;
        }

        public Criteria andWebTitleNotLike(String value) {
            addCriterion("web_title not like", value, "webTitle");
            return (Criteria) this;
        }

        public Criteria andWebTitleIn(List<String> values) {
            addCriterion("web_title in", values, "webTitle");
            return (Criteria) this;
        }

        public Criteria andWebTitleNotIn(List<String> values) {
            addCriterion("web_title not in", values, "webTitle");
            return (Criteria) this;
        }

        public Criteria andWebTitleBetween(String value1, String value2) {
            addCriterion("web_title between", value1, value2, "webTitle");
            return (Criteria) this;
        }

        public Criteria andWebTitleNotBetween(String value1, String value2) {
            addCriterion("web_title not between", value1, value2, "webTitle");
            return (Criteria) this;
        }

        public Criteria andDomainIsNull() {
            addCriterion("domain is null");
            return (Criteria) this;
        }

        public Criteria andDomainIsNotNull() {
            addCriterion("domain is not null");
            return (Criteria) this;
        }

        public Criteria andDomainEqualTo(String value) {
            addCriterion("domain =", value, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainNotEqualTo(String value) {
            addCriterion("domain <>", value, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainGreaterThan(String value) {
            addCriterion("domain >", value, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainGreaterThanOrEqualTo(String value) {
            addCriterion("domain >=", value, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainLessThan(String value) {
            addCriterion("domain <", value, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainLessThanOrEqualTo(String value) {
            addCriterion("domain <=", value, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainLike(String value) {
            addCriterion("domain like", value, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainNotLike(String value) {
            addCriterion("domain not like", value, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainIn(List<String> values) {
            addCriterion("domain in", values, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainNotIn(List<String> values) {
            addCriterion("domain not in", values, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainBetween(String value1, String value2) {
            addCriterion("domain between", value1, value2, "domain");
            return (Criteria) this;
        }

        public Criteria andDomainNotBetween(String value1, String value2) {
            addCriterion("domain not between", value1, value2, "domain");
            return (Criteria) this;
        }

        public Criteria andServiceProductIsNull() {
            addCriterion("service_product is null");
            return (Criteria) this;
        }

        public Criteria andServiceProductIsNotNull() {
            addCriterion("service_product is not null");
            return (Criteria) this;
        }

        public Criteria andServiceProductEqualTo(String value) {
            addCriterion("service_product =", value, "serviceProduct");
            return (Criteria) this;
        }

        public Criteria andServiceProductNotEqualTo(String value) {
            addCriterion("service_product <>", value, "serviceProduct");
            return (Criteria) this;
        }

        public Criteria andServiceProductGreaterThan(String value) {
            addCriterion("service_product >", value, "serviceProduct");
            return (Criteria) this;
        }

        public Criteria andServiceProductGreaterThanOrEqualTo(String value) {
            addCriterion("service_product >=", value, "serviceProduct");
            return (Criteria) this;
        }

        public Criteria andServiceProductLessThan(String value) {
            addCriterion("service_product <", value, "serviceProduct");
            return (Criteria) this;
        }

        public Criteria andServiceProductLessThanOrEqualTo(String value) {
            addCriterion("service_product <=", value, "serviceProduct");
            return (Criteria) this;
        }

        public Criteria andServiceProductLike(String value) {
            addCriterion("service_product like", value, "serviceProduct");
            return (Criteria) this;
        }

        public Criteria andServiceProductNotLike(String value) {
            addCriterion("service_product not like", value, "serviceProduct");
            return (Criteria) this;
        }

        public Criteria andServiceProductIn(List<String> values) {
            addCriterion("service_product in", values, "serviceProduct");
            return (Criteria) this;
        }

        public Criteria andServiceProductNotIn(List<String> values) {
            addCriterion("service_product not in", values, "serviceProduct");
            return (Criteria) this;
        }

        public Criteria andServiceProductBetween(String value1, String value2) {
            addCriterion("service_product between", value1, value2, "serviceProduct");
            return (Criteria) this;
        }

        public Criteria andServiceProductNotBetween(String value1, String value2) {
            addCriterion("service_product not between", value1, value2, "serviceProduct");
            return (Criteria) this;
        }

        public Criteria andServiceVersionIsNull() {
            addCriterion("service_version is null");
            return (Criteria) this;
        }

        public Criteria andServiceVersionIsNotNull() {
            addCriterion("service_version is not null");
            return (Criteria) this;
        }

        public Criteria andServiceVersionEqualTo(String value) {
            addCriterion("service_version =", value, "serviceVersion");
            return (Criteria) this;
        }

        public Criteria andServiceVersionNotEqualTo(String value) {
            addCriterion("service_version <>", value, "serviceVersion");
            return (Criteria) this;
        }

        public Criteria andServiceVersionGreaterThan(String value) {
            addCriterion("service_version >", value, "serviceVersion");
            return (Criteria) this;
        }

        public Criteria andServiceVersionGreaterThanOrEqualTo(String value) {
            addCriterion("service_version >=", value, "serviceVersion");
            return (Criteria) this;
        }

        public Criteria andServiceVersionLessThan(String value) {
            addCriterion("service_version <", value, "serviceVersion");
            return (Criteria) this;
        }

        public Criteria andServiceVersionLessThanOrEqualTo(String value) {
            addCriterion("service_version <=", value, "serviceVersion");
            return (Criteria) this;
        }

        public Criteria andServiceVersionLike(String value) {
            addCriterion("service_version like", value, "serviceVersion");
            return (Criteria) this;
        }

        public Criteria andServiceVersionNotLike(String value) {
            addCriterion("service_version not like", value, "serviceVersion");
            return (Criteria) this;
        }

        public Criteria andServiceVersionIn(List<String> values) {
            addCriterion("service_version in", values, "serviceVersion");
            return (Criteria) this;
        }

        public Criteria andServiceVersionNotIn(List<String> values) {
            addCriterion("service_version not in", values, "serviceVersion");
            return (Criteria) this;
        }

        public Criteria andServiceVersionBetween(String value1, String value2) {
            addCriterion("service_version between", value1, value2, "serviceVersion");
            return (Criteria) this;
        }

        public Criteria andServiceVersionNotBetween(String value1, String value2) {
            addCriterion("service_version not between", value1, value2, "serviceVersion");
            return (Criteria) this;
        }

        public Criteria andDomainCnameIsNull() {
            addCriterion("domain_cname is null");
            return (Criteria) this;
        }

        public Criteria andDomainCnameIsNotNull() {
            addCriterion("domain_cname is not null");
            return (Criteria) this;
        }

        public Criteria andDomainCnameEqualTo(String value) {
            addCriterion("domain_cname =", value, "domainCname");
            return (Criteria) this;
        }

        public Criteria andDomainCnameNotEqualTo(String value) {
            addCriterion("domain_cname <>", value, "domainCname");
            return (Criteria) this;
        }

        public Criteria andDomainCnameGreaterThan(String value) {
            addCriterion("domain_cname >", value, "domainCname");
            return (Criteria) this;
        }

        public Criteria andDomainCnameGreaterThanOrEqualTo(String value) {
            addCriterion("domain_cname >=", value, "domainCname");
            return (Criteria) this;
        }

        public Criteria andDomainCnameLessThan(String value) {
            addCriterion("domain_cname <", value, "domainCname");
            return (Criteria) this;
        }

        public Criteria andDomainCnameLessThanOrEqualTo(String value) {
            addCriterion("domain_cname <=", value, "domainCname");
            return (Criteria) this;
        }

        public Criteria andDomainCnameLike(String value) {
            addCriterion("domain_cname like", value, "domainCname");
            return (Criteria) this;
        }

        public Criteria andDomainCnameNotLike(String value) {
            addCriterion("domain_cname not like", value, "domainCname");
            return (Criteria) this;
        }

        public Criteria andDomainCnameIn(List<String> values) {
            addCriterion("domain_cname in", values, "domainCname");
            return (Criteria) this;
        }

        public Criteria andDomainCnameNotIn(List<String> values) {
            addCriterion("domain_cname not in", values, "domainCname");
            return (Criteria) this;
        }

        public Criteria andDomainCnameBetween(String value1, String value2) {
            addCriterion("domain_cname between", value1, value2, "domainCname");
            return (Criteria) this;
        }

        public Criteria andDomainCnameNotBetween(String value1, String value2) {
            addCriterion("domain_cname not between", value1, value2, "domainCname");
            return (Criteria) this;
        }

        public Criteria andIsCdnIsNull() {
            addCriterion("is_cdn is null");
            return (Criteria) this;
        }

        public Criteria andIsCdnIsNotNull() {
            addCriterion("is_cdn is not null");
            return (Criteria) this;
        }

        public Criteria andIsCdnEqualTo(String value) {
            addCriterion("is_cdn =", value, "isCdn");
            return (Criteria) this;
        }

        public Criteria andIsCdnNotEqualTo(String value) {
            addCriterion("is_cdn <>", value, "isCdn");
            return (Criteria) this;
        }

        public Criteria andIsCdnGreaterThan(String value) {
            addCriterion("is_cdn >", value, "isCdn");
            return (Criteria) this;
        }

        public Criteria andIsCdnGreaterThanOrEqualTo(String value) {
            addCriterion("is_cdn >=", value, "isCdn");
            return (Criteria) this;
        }

        public Criteria andIsCdnLessThan(String value) {
            addCriterion("is_cdn <", value, "isCdn");
            return (Criteria) this;
        }

        public Criteria andIsCdnLessThanOrEqualTo(String value) {
            addCriterion("is_cdn <=", value, "isCdn");
            return (Criteria) this;
        }

        public Criteria andIsCdnLike(String value) {
            addCriterion("is_cdn like", value, "isCdn");
            return (Criteria) this;
        }

        public Criteria andIsCdnNotLike(String value) {
            addCriterion("is_cdn not like", value, "isCdn");
            return (Criteria) this;
        }

        public Criteria andIsCdnIn(List<String> values) {
            addCriterion("is_cdn in", values, "isCdn");
            return (Criteria) this;
        }

        public Criteria andIsCdnNotIn(List<String> values) {
            addCriterion("is_cdn not in", values, "isCdn");
            return (Criteria) this;
        }

        public Criteria andIsCdnBetween(String value1, String value2) {
            addCriterion("is_cdn between", value1, value2, "isCdn");
            return (Criteria) this;
        }

        public Criteria andIsCdnNotBetween(String value1, String value2) {
            addCriterion("is_cdn not between", value1, value2, "isCdn");
            return (Criteria) this;
        }

        public Criteria andCdnProductIsNull() {
            addCriterion("cdn_product is null");
            return (Criteria) this;
        }

        public Criteria andCdnProductIsNotNull() {
            addCriterion("cdn_product is not null");
            return (Criteria) this;
        }

        public Criteria andCdnProductEqualTo(String value) {
            addCriterion("cdn_product =", value, "cdnProduct");
            return (Criteria) this;
        }

        public Criteria andCdnProductNotEqualTo(String value) {
            addCriterion("cdn_product <>", value, "cdnProduct");
            return (Criteria) this;
        }

        public Criteria andCdnProductGreaterThan(String value) {
            addCriterion("cdn_product >", value, "cdnProduct");
            return (Criteria) this;
        }

        public Criteria andCdnProductGreaterThanOrEqualTo(String value) {
            addCriterion("cdn_product >=", value, "cdnProduct");
            return (Criteria) this;
        }

        public Criteria andCdnProductLessThan(String value) {
            addCriterion("cdn_product <", value, "cdnProduct");
            return (Criteria) this;
        }

        public Criteria andCdnProductLessThanOrEqualTo(String value) {
            addCriterion("cdn_product <=", value, "cdnProduct");
            return (Criteria) this;
        }

        public Criteria andCdnProductLike(String value) {
            addCriterion("cdn_product like", value, "cdnProduct");
            return (Criteria) this;
        }

        public Criteria andCdnProductNotLike(String value) {
            addCriterion("cdn_product not like", value, "cdnProduct");
            return (Criteria) this;
        }

        public Criteria andCdnProductIn(List<String> values) {
            addCriterion("cdn_product in", values, "cdnProduct");
            return (Criteria) this;
        }

        public Criteria andCdnProductNotIn(List<String> values) {
            addCriterion("cdn_product not in", values, "cdnProduct");
            return (Criteria) this;
        }

        public Criteria andCdnProductBetween(String value1, String value2) {
            addCriterion("cdn_product between", value1, value2, "cdnProduct");
            return (Criteria) this;
        }

        public Criteria andCdnProductNotBetween(String value1, String value2) {
            addCriterion("cdn_product not between", value1, value2, "cdnProduct");
            return (Criteria) this;
        }

        public Criteria andCdnCompanyIsNull() {
            addCriterion("cdn_company is null");
            return (Criteria) this;
        }

        public Criteria andCdnCompanyIsNotNull() {
            addCriterion("cdn_company is not null");
            return (Criteria) this;
        }

        public Criteria andCdnCompanyEqualTo(String value) {
            addCriterion("cdn_company =", value, "cdnCompany");
            return (Criteria) this;
        }

        public Criteria andCdnCompanyNotEqualTo(String value) {
            addCriterion("cdn_company <>", value, "cdnCompany");
            return (Criteria) this;
        }

        public Criteria andCdnCompanyGreaterThan(String value) {
            addCriterion("cdn_company >", value, "cdnCompany");
            return (Criteria) this;
        }

        public Criteria andCdnCompanyGreaterThanOrEqualTo(String value) {
            addCriterion("cdn_company >=", value, "cdnCompany");
            return (Criteria) this;
        }

        public Criteria andCdnCompanyLessThan(String value) {
            addCriterion("cdn_company <", value, "cdnCompany");
            return (Criteria) this;
        }

        public Criteria andCdnCompanyLessThanOrEqualTo(String value) {
            addCriterion("cdn_company <=", value, "cdnCompany");
            return (Criteria) this;
        }

        public Criteria andCdnCompanyLike(String value) {
            addCriterion("cdn_company like", value, "cdnCompany");
            return (Criteria) this;
        }

        public Criteria andCdnCompanyNotLike(String value) {
            addCriterion("cdn_company not like", value, "cdnCompany");
            return (Criteria) this;
        }

        public Criteria andCdnCompanyIn(List<String> values) {
            addCriterion("cdn_company in", values, "cdnCompany");
            return (Criteria) this;
        }

        public Criteria andCdnCompanyNotIn(List<String> values) {
            addCriterion("cdn_company not in", values, "cdnCompany");
            return (Criteria) this;
        }

        public Criteria andCdnCompanyBetween(String value1, String value2) {
            addCriterion("cdn_company between", value1, value2, "cdnCompany");
            return (Criteria) this;
        }

        public Criteria andCdnCompanyNotBetween(String value1, String value2) {
            addCriterion("cdn_company not between", value1, value2, "cdnCompany");
            return (Criteria) this;
        }

        public Criteria andCdnSslInfoIsNull() {
            addCriterion("cdn_ssl_info is null");
            return (Criteria) this;
        }

        public Criteria andCdnSslInfoIsNotNull() {
            addCriterion("cdn_ssl_info is not null");
            return (Criteria) this;
        }

        public Criteria andCdnSslInfoEqualTo(String value) {
            addCriterion("cdn_ssl_info =", value, "cdnSslInfo");
            return (Criteria) this;
        }

        public Criteria andCdnSslInfoNotEqualTo(String value) {
            addCriterion("cdn_ssl_info <>", value, "cdnSslInfo");
            return (Criteria) this;
        }

        public Criteria andCdnSslInfoGreaterThan(String value) {
            addCriterion("cdn_ssl_info >", value, "cdnSslInfo");
            return (Criteria) this;
        }

        public Criteria andCdnSslInfoGreaterThanOrEqualTo(String value) {
            addCriterion("cdn_ssl_info >=", value, "cdnSslInfo");
            return (Criteria) this;
        }

        public Criteria andCdnSslInfoLessThan(String value) {
            addCriterion("cdn_ssl_info <", value, "cdnSslInfo");
            return (Criteria) this;
        }

        public Criteria andCdnSslInfoLessThanOrEqualTo(String value) {
            addCriterion("cdn_ssl_info <=", value, "cdnSslInfo");
            return (Criteria) this;
        }

        public Criteria andCdnSslInfoLike(String value) {
            addCriterion("cdn_ssl_info like", value, "cdnSslInfo");
            return (Criteria) this;
        }

        public Criteria andCdnSslInfoNotLike(String value) {
            addCriterion("cdn_ssl_info not like", value, "cdnSslInfo");
            return (Criteria) this;
        }

        public Criteria andCdnSslInfoIn(List<String> values) {
            addCriterion("cdn_ssl_info in", values, "cdnSslInfo");
            return (Criteria) this;
        }

        public Criteria andCdnSslInfoNotIn(List<String> values) {
            addCriterion("cdn_ssl_info not in", values, "cdnSslInfo");
            return (Criteria) this;
        }

        public Criteria andCdnSslInfoBetween(String value1, String value2) {
            addCriterion("cdn_ssl_info between", value1, value2, "cdnSslInfo");
            return (Criteria) this;
        }

        public Criteria andCdnSslInfoNotBetween(String value1, String value2) {
            addCriterion("cdn_ssl_info not between", value1, value2, "cdnSslInfo");
            return (Criteria) this;
        }

        public Criteria andResponseHeaderIsNull() {
            addCriterion("response_header is null");
            return (Criteria) this;
        }

        public Criteria andResponseHeaderIsNotNull() {
            addCriterion("response_header is not null");
            return (Criteria) this;
        }

        public Criteria andResponseHeaderEqualTo(String value) {
            addCriterion("response_header =", value, "responseHeader");
            return (Criteria) this;
        }

        public Criteria andResponseHeaderNotEqualTo(String value) {
            addCriterion("response_header <>", value, "responseHeader");
            return (Criteria) this;
        }

        public Criteria andResponseHeaderGreaterThan(String value) {
            addCriterion("response_header >", value, "responseHeader");
            return (Criteria) this;
        }

        public Criteria andResponseHeaderGreaterThanOrEqualTo(String value) {
            addCriterion("response_header >=", value, "responseHeader");
            return (Criteria) this;
        }

        public Criteria andResponseHeaderLessThan(String value) {
            addCriterion("response_header <", value, "responseHeader");
            return (Criteria) this;
        }

        public Criteria andResponseHeaderLessThanOrEqualTo(String value) {
            addCriterion("response_header <=", value, "responseHeader");
            return (Criteria) this;
        }

        public Criteria andResponseHeaderLike(String value) {
            addCriterion("response_header like", value, "responseHeader");
            return (Criteria) this;
        }

        public Criteria andResponseHeaderNotLike(String value) {
            addCriterion("response_header not like", value, "responseHeader");
            return (Criteria) this;
        }

        public Criteria andResponseHeaderIn(List<String> values) {
            addCriterion("response_header in", values, "responseHeader");
            return (Criteria) this;
        }

        public Criteria andResponseHeaderNotIn(List<String> values) {
            addCriterion("response_header not in", values, "responseHeader");
            return (Criteria) this;
        }

        public Criteria andResponseHeaderBetween(String value1, String value2) {
            addCriterion("response_header between", value1, value2, "responseHeader");
            return (Criteria) this;
        }

        public Criteria andResponseHeaderNotBetween(String value1, String value2) {
            addCriterion("response_header not between", value1, value2, "responseHeader");
            return (Criteria) this;
        }

        public Criteria andServerIsNull() {
            addCriterion("server is null");
            return (Criteria) this;
        }

        public Criteria andServerIsNotNull() {
            addCriterion("server is not null");
            return (Criteria) this;
        }

        public Criteria andServerEqualTo(String value) {
            addCriterion("server =", value, "server");
            return (Criteria) this;
        }

        public Criteria andServerNotEqualTo(String value) {
            addCriterion("server <>", value, "server");
            return (Criteria) this;
        }

        public Criteria andServerGreaterThan(String value) {
            addCriterion("server >", value, "server");
            return (Criteria) this;
        }

        public Criteria andServerGreaterThanOrEqualTo(String value) {
            addCriterion("server >=", value, "server");
            return (Criteria) this;
        }

        public Criteria andServerLessThan(String value) {
            addCriterion("server <", value, "server");
            return (Criteria) this;
        }

        public Criteria andServerLessThanOrEqualTo(String value) {
            addCriterion("server <=", value, "server");
            return (Criteria) this;
        }

        public Criteria andServerLike(String value) {
            addCriterion("server like", value, "server");
            return (Criteria) this;
        }

        public Criteria andServerNotLike(String value) {
            addCriterion("server not like", value, "server");
            return (Criteria) this;
        }

        public Criteria andServerIn(List<String> values) {
            addCriterion("server in", values, "server");
            return (Criteria) this;
        }

        public Criteria andServerNotIn(List<String> values) {
            addCriterion("server not in", values, "server");
            return (Criteria) this;
        }

        public Criteria andServerBetween(String value1, String value2) {
            addCriterion("server between", value1, value2, "server");
            return (Criteria) this;
        }

        public Criteria andServerNotBetween(String value1, String value2) {
            addCriterion("server not between", value1, value2, "server");
            return (Criteria) this;
        }

        public Criteria andSslSubjectIsNull() {
            addCriterion("ssl_subject is null");
            return (Criteria) this;
        }

        public Criteria andSslSubjectIsNotNull() {
            addCriterion("ssl_subject is not null");
            return (Criteria) this;
        }

        public Criteria andSslSubjectEqualTo(String value) {
            addCriterion("ssl_subject =", value, "sslSubject");
            return (Criteria) this;
        }

        public Criteria andSslSubjectNotEqualTo(String value) {
            addCriterion("ssl_subject <>", value, "sslSubject");
            return (Criteria) this;
        }

        public Criteria andSslSubjectGreaterThan(String value) {
            addCriterion("ssl_subject >", value, "sslSubject");
            return (Criteria) this;
        }

        public Criteria andSslSubjectGreaterThanOrEqualTo(String value) {
            addCriterion("ssl_subject >=", value, "sslSubject");
            return (Criteria) this;
        }

        public Criteria andSslSubjectLessThan(String value) {
            addCriterion("ssl_subject <", value, "sslSubject");
            return (Criteria) this;
        }

        public Criteria andSslSubjectLessThanOrEqualTo(String value) {
            addCriterion("ssl_subject <=", value, "sslSubject");
            return (Criteria) this;
        }

        public Criteria andSslSubjectLike(String value) {
            addCriterion("ssl_subject like", value, "sslSubject");
            return (Criteria) this;
        }

        public Criteria andSslSubjectNotLike(String value) {
            addCriterion("ssl_subject not like", value, "sslSubject");
            return (Criteria) this;
        }

        public Criteria andSslSubjectIn(List<String> values) {
            addCriterion("ssl_subject in", values, "sslSubject");
            return (Criteria) this;
        }

        public Criteria andSslSubjectNotIn(List<String> values) {
            addCriterion("ssl_subject not in", values, "sslSubject");
            return (Criteria) this;
        }

        public Criteria andSslSubjectBetween(String value1, String value2) {
            addCriterion("ssl_subject between", value1, value2, "sslSubject");
            return (Criteria) this;
        }

        public Criteria andSslSubjectNotBetween(String value1, String value2) {
            addCriterion("ssl_subject not between", value1, value2, "sslSubject");
            return (Criteria) this;
        }

        public Criteria andServiceBannerIsNull() {
            addCriterion("service_banner is null");
            return (Criteria) this;
        }

        public Criteria andServiceBannerIsNotNull() {
            addCriterion("service_banner is not null");
            return (Criteria) this;
        }

        public Criteria andServiceBannerEqualTo(String value) {
            addCriterion("service_banner =", value, "serviceBanner");
            return (Criteria) this;
        }

        public Criteria andServiceBannerNotEqualTo(String value) {
            addCriterion("service_banner <>", value, "serviceBanner");
            return (Criteria) this;
        }

        public Criteria andServiceBannerGreaterThan(String value) {
            addCriterion("service_banner >", value, "serviceBanner");
            return (Criteria) this;
        }

        public Criteria andServiceBannerGreaterThanOrEqualTo(String value) {
            addCriterion("service_banner >=", value, "serviceBanner");
            return (Criteria) this;
        }

        public Criteria andServiceBannerLessThan(String value) {
            addCriterion("service_banner <", value, "serviceBanner");
            return (Criteria) this;
        }

        public Criteria andServiceBannerLessThanOrEqualTo(String value) {
            addCriterion("service_banner <=", value, "serviceBanner");
            return (Criteria) this;
        }

        public Criteria andServiceBannerLike(String value) {
            addCriterion("service_banner like", value, "serviceBanner");
            return (Criteria) this;
        }

        public Criteria andServiceBannerNotLike(String value) {
            addCriterion("service_banner not like", value, "serviceBanner");
            return (Criteria) this;
        }

        public Criteria andServiceBannerIn(List<String> values) {
            addCriterion("service_banner in", values, "serviceBanner");
            return (Criteria) this;
        }

        public Criteria andServiceBannerNotIn(List<String> values) {
            addCriterion("service_banner not in", values, "serviceBanner");
            return (Criteria) this;
        }

        public Criteria andServiceBannerBetween(String value1, String value2) {
            addCriterion("service_banner between", value1, value2, "serviceBanner");
            return (Criteria) this;
        }

        public Criteria andServiceBannerNotBetween(String value1, String value2) {
            addCriterion("service_banner not between", value1, value2, "serviceBanner");
            return (Criteria) this;
        }

        public Criteria andPDeviceTypeIsNull() {
            addCriterion("p_device_type is null");
            return (Criteria) this;
        }

        public Criteria andPDeviceTypeIsNotNull() {
            addCriterion("p_device_type is not null");
            return (Criteria) this;
        }

        public Criteria andPDeviceTypeEqualTo(String value) {
            addCriterion("p_device_type =", value, "pDeviceType");
            return (Criteria) this;
        }

        public Criteria andPDeviceTypeNotEqualTo(String value) {
            addCriterion("p_device_type <>", value, "pDeviceType");
            return (Criteria) this;
        }

        public Criteria andPDeviceTypeGreaterThan(String value) {
            addCriterion("p_device_type >", value, "pDeviceType");
            return (Criteria) this;
        }

        public Criteria andPDeviceTypeGreaterThanOrEqualTo(String value) {
            addCriterion("p_device_type >=", value, "pDeviceType");
            return (Criteria) this;
        }

        public Criteria andPDeviceTypeLessThan(String value) {
            addCriterion("p_device_type <", value, "pDeviceType");
            return (Criteria) this;
        }

        public Criteria andPDeviceTypeLessThanOrEqualTo(String value) {
            addCriterion("p_device_type <=", value, "pDeviceType");
            return (Criteria) this;
        }

        public Criteria andPDeviceTypeLike(String value) {
            addCriterion("p_device_type like", value, "pDeviceType");
            return (Criteria) this;
        }

        public Criteria andPDeviceTypeNotLike(String value) {
            addCriterion("p_device_type not like", value, "pDeviceType");
            return (Criteria) this;
        }

        public Criteria andPDeviceTypeIn(List<String> values) {
            addCriterion("p_device_type in", values, "pDeviceType");
            return (Criteria) this;
        }

        public Criteria andPDeviceTypeNotIn(List<String> values) {
            addCriterion("p_device_type not in", values, "pDeviceType");
            return (Criteria) this;
        }

        public Criteria andPDeviceTypeBetween(String value1, String value2) {
            addCriterion("p_device_type between", value1, value2, "pDeviceType");
            return (Criteria) this;
        }

        public Criteria andPDeviceTypeNotBetween(String value1, String value2) {
            addCriterion("p_device_type not between", value1, value2, "pDeviceType");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeIsNull() {
            addCriterion("device_type is null");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeIsNotNull() {
            addCriterion("device_type is not null");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeEqualTo(String value) {
            addCriterion("device_type =", value, "deviceType");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeNotEqualTo(String value) {
            addCriterion("device_type <>", value, "deviceType");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeGreaterThan(String value) {
            addCriterion("device_type >", value, "deviceType");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeGreaterThanOrEqualTo(String value) {
            addCriterion("device_type >=", value, "deviceType");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeLessThan(String value) {
            addCriterion("device_type <", value, "deviceType");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeLessThanOrEqualTo(String value) {
            addCriterion("device_type <=", value, "deviceType");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeLike(String value) {
            addCriterion("device_type like", value, "deviceType");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeNotLike(String value) {
            addCriterion("device_type not like", value, "deviceType");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeIn(List<String> values) {
            addCriterion("device_type in", values, "deviceType");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeNotIn(List<String> values) {
            addCriterion("device_type not in", values, "deviceType");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeBetween(String value1, String value2) {
            addCriterion("device_type between", value1, value2, "deviceType");
            return (Criteria) this;
        }

        public Criteria andDeviceTypeNotBetween(String value1, String value2) {
            addCriterion("device_type not between", value1, value2, "deviceType");
            return (Criteria) this;
        }

        public Criteria andScanTimeIsNull() {
            addCriterion("scan_time is null");
            return (Criteria) this;
        }

        public Criteria andScanTimeIsNotNull() {
            addCriterion("scan_time is not null");
            return (Criteria) this;
        }

        public Criteria andScanTimeEqualTo(String value) {
            addCriterion("scan_time =", value, "scanTime");
            return (Criteria) this;
        }

        public Criteria andScanTimeNotEqualTo(String value) {
            addCriterion("scan_time <>", value, "scanTime");
            return (Criteria) this;
        }

        public Criteria andScanTimeGreaterThan(String value) {
            addCriterion("scan_time >", value, "scanTime");
            return (Criteria) this;
        }

        public Criteria andScanTimeGreaterThanOrEqualTo(String value) {
            addCriterion("scan_time >=", value, "scanTime");
            return (Criteria) this;
        }

        public Criteria andScanTimeLessThan(String value) {
            addCriterion("scan_time <", value, "scanTime");
            return (Criteria) this;
        }

        public Criteria andScanTimeLessThanOrEqualTo(String value) {
            addCriterion("scan_time <=", value, "scanTime");
            return (Criteria) this;
        }

        public Criteria andScanTimeLike(String value) {
            addCriterion("scan_time like", value, "scanTime");
            return (Criteria) this;
        }

        public Criteria andScanTimeNotLike(String value) {
            addCriterion("scan_time not like", value, "scanTime");
            return (Criteria) this;
        }

        public Criteria andScanTimeIn(List<String> values) {
            addCriterion("scan_time in", values, "scanTime");
            return (Criteria) this;
        }

        public Criteria andScanTimeNotIn(List<String> values) {
            addCriterion("scan_time not in", values, "scanTime");
            return (Criteria) this;
        }

        public Criteria andScanTimeBetween(String value1, String value2) {
            addCriterion("scan_time between", value1, value2, "scanTime");
            return (Criteria) this;
        }

        public Criteria andScanTimeNotBetween(String value1, String value2) {
            addCriterion("scan_time not between", value1, value2, "scanTime");
            return (Criteria) this;
        }

        public Criteria andCountryIsNull() {
            addCriterion("country is null");
            return (Criteria) this;
        }

        public Criteria andCountryIsNotNull() {
            addCriterion("country is not null");
            return (Criteria) this;
        }

        public Criteria andCountryEqualTo(String value) {
            addCriterion("country =", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotEqualTo(String value) {
            addCriterion("country <>", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryGreaterThan(String value) {
            addCriterion("country >", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryGreaterThanOrEqualTo(String value) {
            addCriterion("country >=", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryLessThan(String value) {
            addCriterion("country <", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryLessThanOrEqualTo(String value) {
            addCriterion("country <=", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryLike(String value) {
            addCriterion("country like", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotLike(String value) {
            addCriterion("country not like", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryIn(List<String> values) {
            addCriterion("country in", values, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotIn(List<String> values) {
            addCriterion("country not in", values, "country");
            return (Criteria) this;
        }

        public Criteria andCountryBetween(String value1, String value2) {
            addCriterion("country between", value1, value2, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotBetween(String value1, String value2) {
            addCriterion("country not between", value1, value2, "country");
            return (Criteria) this;
        }

        public Criteria andProvinceIsNull() {
            addCriterion("province is null");
            return (Criteria) this;
        }

        public Criteria andProvinceIsNotNull() {
            addCriterion("province is not null");
            return (Criteria) this;
        }

        public Criteria andProvinceEqualTo(String value) {
            addCriterion("province =", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotEqualTo(String value) {
            addCriterion("province <>", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceGreaterThan(String value) {
            addCriterion("province >", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceGreaterThanOrEqualTo(String value) {
            addCriterion("province >=", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLessThan(String value) {
            addCriterion("province <", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLessThanOrEqualTo(String value) {
            addCriterion("province <=", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLike(String value) {
            addCriterion("province like", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotLike(String value) {
            addCriterion("province not like", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceIn(List<String> values) {
            addCriterion("province in", values, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotIn(List<String> values) {
            addCriterion("province not in", values, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceBetween(String value1, String value2) {
            addCriterion("province between", value1, value2, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotBetween(String value1, String value2) {
            addCriterion("province not between", value1, value2, "province");
            return (Criteria) this;
        }

        public Criteria andIsAliveIsNull() {
            addCriterion("is_alive is null");
            return (Criteria) this;
        }

        public Criteria andIsAliveIsNotNull() {
            addCriterion("is_alive is not null");
            return (Criteria) this;
        }

        public Criteria andIsAliveEqualTo(String value) {
            addCriterion("is_alive =", value, "isAlive");
            return (Criteria) this;
        }

        public Criteria andIsAliveNotEqualTo(String value) {
            addCriterion("is_alive <>", value, "isAlive");
            return (Criteria) this;
        }

        public Criteria andIsAliveGreaterThan(String value) {
            addCriterion("is_alive >", value, "isAlive");
            return (Criteria) this;
        }

        public Criteria andIsAliveGreaterThanOrEqualTo(String value) {
            addCriterion("is_alive >=", value, "isAlive");
            return (Criteria) this;
        }

        public Criteria andIsAliveLessThan(String value) {
            addCriterion("is_alive <", value, "isAlive");
            return (Criteria) this;
        }

        public Criteria andIsAliveLessThanOrEqualTo(String value) {
            addCriterion("is_alive <=", value, "isAlive");
            return (Criteria) this;
        }

        public Criteria andIsAliveLike(String value) {
            addCriterion("is_alive like", value, "isAlive");
            return (Criteria) this;
        }

        public Criteria andIsAliveNotLike(String value) {
            addCriterion("is_alive not like", value, "isAlive");
            return (Criteria) this;
        }

        public Criteria andIsAliveIn(List<String> values) {
            addCriterion("is_alive in", values, "isAlive");
            return (Criteria) this;
        }

        public Criteria andIsAliveNotIn(List<String> values) {
            addCriterion("is_alive not in", values, "isAlive");
            return (Criteria) this;
        }

        public Criteria andIsAliveBetween(String value1, String value2) {
            addCriterion("is_alive between", value1, value2, "isAlive");
            return (Criteria) this;
        }

        public Criteria andIsAliveNotBetween(String value1, String value2) {
            addCriterion("is_alive not between", value1, value2, "isAlive");
            return (Criteria) this;
        }

        public Criteria andClassify1IsNull() {
            addCriterion("classify_1 is null");
            return (Criteria) this;
        }

        public Criteria andClassify1IsNotNull() {
            addCriterion("classify_1 is not null");
            return (Criteria) this;
        }

        public Criteria andClassify1EqualTo(String value) {
            addCriterion("classify_1 =", value, "classify1");
            return (Criteria) this;
        }

        public Criteria andClassify1NotEqualTo(String value) {
            addCriterion("classify_1 <>", value, "classify1");
            return (Criteria) this;
        }

        public Criteria andClassify1GreaterThan(String value) {
            addCriterion("classify_1 >", value, "classify1");
            return (Criteria) this;
        }

        public Criteria andClassify1GreaterThanOrEqualTo(String value) {
            addCriterion("classify_1 >=", value, "classify1");
            return (Criteria) this;
        }

        public Criteria andClassify1LessThan(String value) {
            addCriterion("classify_1 <", value, "classify1");
            return (Criteria) this;
        }

        public Criteria andClassify1LessThanOrEqualTo(String value) {
            addCriterion("classify_1 <=", value, "classify1");
            return (Criteria) this;
        }

        public Criteria andClassify1Like(String value) {
            addCriterion("classify_1 like", value, "classify1");
            return (Criteria) this;
        }

        public Criteria andClassify1NotLike(String value) {
            addCriterion("classify_1 not like", value, "classify1");
            return (Criteria) this;
        }

        public Criteria andClassify1In(List<String> values) {
            addCriterion("classify_1 in", values, "classify1");
            return (Criteria) this;
        }

        public Criteria andClassify1NotIn(List<String> values) {
            addCriterion("classify_1 not in", values, "classify1");
            return (Criteria) this;
        }

        public Criteria andClassify1Between(String value1, String value2) {
            addCriterion("classify_1 between", value1, value2, "classify1");
            return (Criteria) this;
        }

        public Criteria andClassify1NotBetween(String value1, String value2) {
            addCriterion("classify_1 not between", value1, value2, "classify1");
            return (Criteria) this;
        }

        public Criteria andClassify2IsNull() {
            addCriterion("classify_2 is null");
            return (Criteria) this;
        }

        public Criteria andClassify2IsNotNull() {
            addCriterion("classify_2 is not null");
            return (Criteria) this;
        }

        public Criteria andClassify2EqualTo(String value) {
            addCriterion("classify_2 =", value, "classify2");
            return (Criteria) this;
        }

        public Criteria andClassify2NotEqualTo(String value) {
            addCriterion("classify_2 <>", value, "classify2");
            return (Criteria) this;
        }

        public Criteria andClassify2GreaterThan(String value) {
            addCriterion("classify_2 >", value, "classify2");
            return (Criteria) this;
        }

        public Criteria andClassify2GreaterThanOrEqualTo(String value) {
            addCriterion("classify_2 >=", value, "classify2");
            return (Criteria) this;
        }

        public Criteria andClassify2LessThan(String value) {
            addCriterion("classify_2 <", value, "classify2");
            return (Criteria) this;
        }

        public Criteria andClassify2LessThanOrEqualTo(String value) {
            addCriterion("classify_2 <=", value, "classify2");
            return (Criteria) this;
        }

        public Criteria andClassify2Like(String value) {
            addCriterion("classify_2 like", value, "classify2");
            return (Criteria) this;
        }

        public Criteria andClassify2NotLike(String value) {
            addCriterion("classify_2 not like", value, "classify2");
            return (Criteria) this;
        }

        public Criteria andClassify2In(List<String> values) {
            addCriterion("classify_2 in", values, "classify2");
            return (Criteria) this;
        }

        public Criteria andClassify2NotIn(List<String> values) {
            addCriterion("classify_2 not in", values, "classify2");
            return (Criteria) this;
        }

        public Criteria andClassify2Between(String value1, String value2) {
            addCriterion("classify_2 between", value1, value2, "classify2");
            return (Criteria) this;
        }

        public Criteria andClassify2NotBetween(String value1, String value2) {
            addCriterion("classify_2 not between", value1, value2, "classify2");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table asset_detect_data
     *
     * @mbg.generated do_not_delete_during_merge Wed May 29 17:01:13 CST 2024
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table asset_detect_data
     *
     * @mbg.generated Wed May 29 17:01:13 CST 2024
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}