package com.pinyougou.pojo;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table central_office_service_information
 */
public class CentralOfficeServiceInformation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column central_office_service_information.id
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   资产上报ID 探测到的业务信息系统填写UUID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column central_office_service_information.sys_id
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    private String sysId;

    /**
     * Database Column Remarks:
     *   系统名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column central_office_service_information.sys_name
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    private String sysName;

    /**
     * Database Column Remarks:
     *   上线时间   YYYY-MM-DDhh:mm:ss（英文半角格式）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column central_office_service_information.launch_time
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    private Date launchTime;

    /**
     * Database Column Remarks:
     *   系统类型编码   探测也必填
     *   0：公众服务系统，如面向公众的水电费缴费系统、银行支付清算系统、网上购票系统等；
     *   1：业务信息系统，如电力配送业务系统、银行运营业务系统、交通指挥业务系统、工业生产制造系统等；
     *   2：办公管理系统，如企事业单位oa系统等；
     *   3：网站，如党政机关网站、企事业单位网站、新闻网站信息发布网站；
     *   4：其他
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column central_office_service_information.sys_type
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    private String sysType;

    /**
     * Database Column Remarks:
     *   系统版本
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column central_office_service_information.sys_version
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    private String sysVersion;

    /**
     * Database Column Remarks:
     *   系统简介
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column central_office_service_information.description
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    private String description;

    /**
     * Database Column Remarks:
     *   系统使用域名列表
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column central_office_service_information.domain_list
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    private String domainList;

    /**
     * Database Column Remarks:
     *   系统使用ip端口列表   
     *   ip地址列表，列表元素为string类型。ipv4地址用“点分十进制”表示，ipv6地址用“冒分十六进制”表示，前导0请勿省略。如果没开端口，则port填-1。取值如下[ip1:port1|port2|…|port3, ip2:port1,…]
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column central_office_service_information.ip_port_list
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    private String ipPortList;

    /**
     * Database Column Remarks:
     *   系统使用url
     *   ip、域名、url（至少一个必填），列表元素为string类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column central_office_service_information.url_list
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    private String urlList;

    /**
     * Database Column Remarks:
     *   系统的dns服务器域名列表   dns列表，列表元素为string类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column central_office_service_information.dns_list
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    private String dnsList;

    /**
     * Database Column Remarks:
     *   等保级别
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column central_office_service_information.protect_level
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    private String protectLevel;

    /**
     * Database Column Remarks:
     *   系统截图
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column central_office_service_information.snapshot
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    private String snapshot;

    /**
     * Database Column Remarks:
     *   是否为关键信息基础设施 
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column central_office_service_information.is_critical_info_infra
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    private Integer isCriticalInfoInfra;

    /**
     * Database Column Remarks:
     *   系统所属行业编码    取值见附表A.3
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column central_office_service_information.industry_code
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    private String industryCode;

    /**
     * Database Column Remarks:
     *   关键业务编码  取值见附表A.4
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column central_office_service_information.business_code
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    private String businessCode;

    /**
     * Database Column Remarks:
     *   icp备案状态    未备案：0，已备案：备案号，非网站系统：-1
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column central_office_service_information.icp_code
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    private String icpCode;

    /**
     * Database Column Remarks:
     *   系统所属单位统一社会信用代码    与表1的organization_code字段关联
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column central_office_service_information.organization_code
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    private String organizationCode;

    /**
     * Database Column Remarks:
     *   系统责任人姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column central_office_service_information.contact_name
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    private String contactName;

    /**
     * Database Column Remarks:
     *   系统责任人联系电话
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column central_office_service_information.contact_phone
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    private String contactPhone;

    /**
     * Database Column Remarks:
     *   系统责任人联系邮箱
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column central_office_service_information.contact_email
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    private String contactEmail;

    /**
     * Database Column Remarks:
     *   系统责任人联系地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column central_office_service_information.contact_address
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    private String contactAddress;

    /**
     * Database Column Remarks:
     *   重要性  非常重要：3；重要：2；一般：1  
     *   非常重要：业务系统是关键信息基础设施设施，或用户规模为百万以上，等保级别为3,4,5级；
     *   重要：业务系统非关键信息基础设施，或用户规模在十万到百万之间，或等保级别为2级；
     *   一般：业务系统非关键信息基础设施，或用户规模在十万以下，或等保级别为1级。
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column central_office_service_information.significance
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    private Integer significance;

    /**
     * Database Column Remarks:
     *   服务对象列表    服务对象为个人用户服务，编码为“0”；服务对象为组织机构服务，编码为“1”；支撑其他平台运行，编码为“2”；其他编码为“3”。可以是列表形式，多个对象,列表元素为int类型。
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column central_office_service_information.serve_object_list
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    private String serveObjectList;

    /**
     * Database Column Remarks:
     *   用户规模   10000人以下，取值为0；10001-100000人，取值为1；100001-1000000人，取值为2；1000001人及以上，取值为3
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column central_office_service_information.user_num
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    private Integer userNum;

    /**
     * Database Column Remarks:
     *   是否连接互联网
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column central_office_service_information.is_inter_connect
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    private Integer isInterConnect;

    /**
     * Database Column Remarks:
     *   来源 0：上报；1：探测
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column central_office_service_information.source
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    private String source;

    /**
     * Database Column Remarks:
     *   数据报送动作 0：新增；1：更新；2：删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column central_office_service_information.action
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    private Integer action;

    /**
     * Database Column Remarks:
     *   是否删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column central_office_service_information.is_deleted
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    private Integer isDeleted;

    /**
     * Database Column Remarks:
     *   创建人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column central_office_service_information.create_user
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    private String createUser;

    /**
     * Database Column Remarks:
     *   创建人名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column central_office_service_information.create_name
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    private String createName;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column central_office_service_information.create_time
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   操作人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column central_office_service_information.update_user
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    private String updateUser;

    /**
     * Database Column Remarks:
     *   操作人名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column central_office_service_information.update_name
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    private String updateName;

    /**
     * Database Column Remarks:
     *   操作时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column central_office_service_information.update_time
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   日期
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column central_office_service_information.day
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    private Date day;

    /**
     * Database Column Remarks:
     *   审核状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column central_office_service_information.audit_status
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    private Integer auditStatus;

    /**
     * Database Column Remarks:
     *   审核时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column central_office_service_information.audit_time
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    private Date auditTime;

    /**
     * Database Column Remarks:
     *   审核用户
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column central_office_service_information.audit_user
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    private String auditUser;

    /**
     * Database Column Remarks:
     *   审核用户名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column central_office_service_information.audit_name
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    private String auditName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column central_office_service_information.id
     *
     * @return the value of central_office_service_information.id
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column central_office_service_information.id
     *
     * @param id the value for central_office_service_information.id
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column central_office_service_information.sys_id
     *
     * @return the value of central_office_service_information.sys_id
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public String getSysId() {
        return sysId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column central_office_service_information.sys_id
     *
     * @param sysId the value for central_office_service_information.sys_id
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public void setSysId(String sysId) {
        this.sysId = sysId == null ? null : sysId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column central_office_service_information.sys_name
     *
     * @return the value of central_office_service_information.sys_name
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public String getSysName() {
        return sysName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column central_office_service_information.sys_name
     *
     * @param sysName the value for central_office_service_information.sys_name
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public void setSysName(String sysName) {
        this.sysName = sysName == null ? null : sysName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column central_office_service_information.launch_time
     *
     * @return the value of central_office_service_information.launch_time
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public Date getLaunchTime() {
        return launchTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column central_office_service_information.launch_time
     *
     * @param launchTime the value for central_office_service_information.launch_time
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public void setLaunchTime(Date launchTime) {
        this.launchTime = launchTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column central_office_service_information.sys_type
     *
     * @return the value of central_office_service_information.sys_type
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public String getSysType() {
        return sysType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column central_office_service_information.sys_type
     *
     * @param sysType the value for central_office_service_information.sys_type
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public void setSysType(String sysType) {
        this.sysType = sysType == null ? null : sysType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column central_office_service_information.sys_version
     *
     * @return the value of central_office_service_information.sys_version
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public String getSysVersion() {
        return sysVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column central_office_service_information.sys_version
     *
     * @param sysVersion the value for central_office_service_information.sys_version
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public void setSysVersion(String sysVersion) {
        this.sysVersion = sysVersion == null ? null : sysVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column central_office_service_information.description
     *
     * @return the value of central_office_service_information.description
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column central_office_service_information.description
     *
     * @param description the value for central_office_service_information.description
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column central_office_service_information.domain_list
     *
     * @return the value of central_office_service_information.domain_list
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public String getDomainList() {
        return domainList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column central_office_service_information.domain_list
     *
     * @param domainList the value for central_office_service_information.domain_list
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public void setDomainList(String domainList) {
        this.domainList = domainList == null ? null : domainList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column central_office_service_information.ip_port_list
     *
     * @return the value of central_office_service_information.ip_port_list
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public String getIpPortList() {
        return ipPortList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column central_office_service_information.ip_port_list
     *
     * @param ipPortList the value for central_office_service_information.ip_port_list
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public void setIpPortList(String ipPortList) {
        this.ipPortList = ipPortList == null ? null : ipPortList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column central_office_service_information.url_list
     *
     * @return the value of central_office_service_information.url_list
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public String getUrlList() {
        return urlList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column central_office_service_information.url_list
     *
     * @param urlList the value for central_office_service_information.url_list
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public void setUrlList(String urlList) {
        this.urlList = urlList == null ? null : urlList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column central_office_service_information.dns_list
     *
     * @return the value of central_office_service_information.dns_list
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public String getDnsList() {
        return dnsList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column central_office_service_information.dns_list
     *
     * @param dnsList the value for central_office_service_information.dns_list
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public void setDnsList(String dnsList) {
        this.dnsList = dnsList == null ? null : dnsList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column central_office_service_information.protect_level
     *
     * @return the value of central_office_service_information.protect_level
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public String getProtectLevel() {
        return protectLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column central_office_service_information.protect_level
     *
     * @param protectLevel the value for central_office_service_information.protect_level
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public void setProtectLevel(String protectLevel) {
        this.protectLevel = protectLevel == null ? null : protectLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column central_office_service_information.snapshot
     *
     * @return the value of central_office_service_information.snapshot
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public String getSnapshot() {
        return snapshot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column central_office_service_information.snapshot
     *
     * @param snapshot the value for central_office_service_information.snapshot
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public void setSnapshot(String snapshot) {
        this.snapshot = snapshot == null ? null : snapshot.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column central_office_service_information.is_critical_info_infra
     *
     * @return the value of central_office_service_information.is_critical_info_infra
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public Integer getIsCriticalInfoInfra() {
        return isCriticalInfoInfra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column central_office_service_information.is_critical_info_infra
     *
     * @param isCriticalInfoInfra the value for central_office_service_information.is_critical_info_infra
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public void setIsCriticalInfoInfra(Integer isCriticalInfoInfra) {
        this.isCriticalInfoInfra = isCriticalInfoInfra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column central_office_service_information.industry_code
     *
     * @return the value of central_office_service_information.industry_code
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public String getIndustryCode() {
        return industryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column central_office_service_information.industry_code
     *
     * @param industryCode the value for central_office_service_information.industry_code
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public void setIndustryCode(String industryCode) {
        this.industryCode = industryCode == null ? null : industryCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column central_office_service_information.business_code
     *
     * @return the value of central_office_service_information.business_code
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public String getBusinessCode() {
        return businessCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column central_office_service_information.business_code
     *
     * @param businessCode the value for central_office_service_information.business_code
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public void setBusinessCode(String businessCode) {
        this.businessCode = businessCode == null ? null : businessCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column central_office_service_information.icp_code
     *
     * @return the value of central_office_service_information.icp_code
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public String getIcpCode() {
        return icpCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column central_office_service_information.icp_code
     *
     * @param icpCode the value for central_office_service_information.icp_code
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public void setIcpCode(String icpCode) {
        this.icpCode = icpCode == null ? null : icpCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column central_office_service_information.organization_code
     *
     * @return the value of central_office_service_information.organization_code
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public String getOrganizationCode() {
        return organizationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column central_office_service_information.organization_code
     *
     * @param organizationCode the value for central_office_service_information.organization_code
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public void setOrganizationCode(String organizationCode) {
        this.organizationCode = organizationCode == null ? null : organizationCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column central_office_service_information.contact_name
     *
     * @return the value of central_office_service_information.contact_name
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public String getContactName() {
        return contactName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column central_office_service_information.contact_name
     *
     * @param contactName the value for central_office_service_information.contact_name
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public void setContactName(String contactName) {
        this.contactName = contactName == null ? null : contactName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column central_office_service_information.contact_phone
     *
     * @return the value of central_office_service_information.contact_phone
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public String getContactPhone() {
        return contactPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column central_office_service_information.contact_phone
     *
     * @param contactPhone the value for central_office_service_information.contact_phone
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public void setContactPhone(String contactPhone) {
        this.contactPhone = contactPhone == null ? null : contactPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column central_office_service_information.contact_email
     *
     * @return the value of central_office_service_information.contact_email
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public String getContactEmail() {
        return contactEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column central_office_service_information.contact_email
     *
     * @param contactEmail the value for central_office_service_information.contact_email
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public void setContactEmail(String contactEmail) {
        this.contactEmail = contactEmail == null ? null : contactEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column central_office_service_information.contact_address
     *
     * @return the value of central_office_service_information.contact_address
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public String getContactAddress() {
        return contactAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column central_office_service_information.contact_address
     *
     * @param contactAddress the value for central_office_service_information.contact_address
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public void setContactAddress(String contactAddress) {
        this.contactAddress = contactAddress == null ? null : contactAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column central_office_service_information.significance
     *
     * @return the value of central_office_service_information.significance
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public Integer getSignificance() {
        return significance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column central_office_service_information.significance
     *
     * @param significance the value for central_office_service_information.significance
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public void setSignificance(Integer significance) {
        this.significance = significance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column central_office_service_information.serve_object_list
     *
     * @return the value of central_office_service_information.serve_object_list
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public String getServeObjectList() {
        return serveObjectList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column central_office_service_information.serve_object_list
     *
     * @param serveObjectList the value for central_office_service_information.serve_object_list
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public void setServeObjectList(String serveObjectList) {
        this.serveObjectList = serveObjectList == null ? null : serveObjectList.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column central_office_service_information.user_num
     *
     * @return the value of central_office_service_information.user_num
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public Integer getUserNum() {
        return userNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column central_office_service_information.user_num
     *
     * @param userNum the value for central_office_service_information.user_num
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public void setUserNum(Integer userNum) {
        this.userNum = userNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column central_office_service_information.is_inter_connect
     *
     * @return the value of central_office_service_information.is_inter_connect
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public Integer getIsInterConnect() {
        return isInterConnect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column central_office_service_information.is_inter_connect
     *
     * @param isInterConnect the value for central_office_service_information.is_inter_connect
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public void setIsInterConnect(Integer isInterConnect) {
        this.isInterConnect = isInterConnect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column central_office_service_information.source
     *
     * @return the value of central_office_service_information.source
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column central_office_service_information.source
     *
     * @param source the value for central_office_service_information.source
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column central_office_service_information.action
     *
     * @return the value of central_office_service_information.action
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public Integer getAction() {
        return action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column central_office_service_information.action
     *
     * @param action the value for central_office_service_information.action
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public void setAction(Integer action) {
        this.action = action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column central_office_service_information.is_deleted
     *
     * @return the value of central_office_service_information.is_deleted
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column central_office_service_information.is_deleted
     *
     * @param isDeleted the value for central_office_service_information.is_deleted
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column central_office_service_information.create_user
     *
     * @return the value of central_office_service_information.create_user
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column central_office_service_information.create_user
     *
     * @param createUser the value for central_office_service_information.create_user
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column central_office_service_information.create_name
     *
     * @return the value of central_office_service_information.create_name
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public String getCreateName() {
        return createName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column central_office_service_information.create_name
     *
     * @param createName the value for central_office_service_information.create_name
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public void setCreateName(String createName) {
        this.createName = createName == null ? null : createName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column central_office_service_information.create_time
     *
     * @return the value of central_office_service_information.create_time
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column central_office_service_information.create_time
     *
     * @param createTime the value for central_office_service_information.create_time
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column central_office_service_information.update_user
     *
     * @return the value of central_office_service_information.update_user
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column central_office_service_information.update_user
     *
     * @param updateUser the value for central_office_service_information.update_user
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column central_office_service_information.update_name
     *
     * @return the value of central_office_service_information.update_name
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public String getUpdateName() {
        return updateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column central_office_service_information.update_name
     *
     * @param updateName the value for central_office_service_information.update_name
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public void setUpdateName(String updateName) {
        this.updateName = updateName == null ? null : updateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column central_office_service_information.update_time
     *
     * @return the value of central_office_service_information.update_time
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column central_office_service_information.update_time
     *
     * @param updateTime the value for central_office_service_information.update_time
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column central_office_service_information.day
     *
     * @return the value of central_office_service_information.day
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public Date getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column central_office_service_information.day
     *
     * @param day the value for central_office_service_information.day
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public void setDay(Date day) {
        this.day = day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column central_office_service_information.audit_status
     *
     * @return the value of central_office_service_information.audit_status
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public Integer getAuditStatus() {
        return auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column central_office_service_information.audit_status
     *
     * @param auditStatus the value for central_office_service_information.audit_status
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public void setAuditStatus(Integer auditStatus) {
        this.auditStatus = auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column central_office_service_information.audit_time
     *
     * @return the value of central_office_service_information.audit_time
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public Date getAuditTime() {
        return auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column central_office_service_information.audit_time
     *
     * @param auditTime the value for central_office_service_information.audit_time
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public void setAuditTime(Date auditTime) {
        this.auditTime = auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column central_office_service_information.audit_user
     *
     * @return the value of central_office_service_information.audit_user
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public String getAuditUser() {
        return auditUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column central_office_service_information.audit_user
     *
     * @param auditUser the value for central_office_service_information.audit_user
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public void setAuditUser(String auditUser) {
        this.auditUser = auditUser == null ? null : auditUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column central_office_service_information.audit_name
     *
     * @return the value of central_office_service_information.audit_name
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public String getAuditName() {
        return auditName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column central_office_service_information.audit_name
     *
     * @param auditName the value for central_office_service_information.audit_name
     *
     * @mbg.generated Wed May 29 18:23:01 CST 2024
     */
    public void setAuditName(String auditName) {
        this.auditName = auditName == null ? null : auditName.trim();
    }
}